# This file defines the list of Applications to serve
# Use the unique id from the persons.toml file when defining the author and owner.
[home]
name = "Home"
introduction = "The landing page of the site"
description = "The landing page introduces the site and provides navigation"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "/"
servable = "src/apps/home/app.py"
thumbnail_url = "assets/images/thumbnails/home.png"
tags = []
category = "Main"
documentation_url = ""
code_url = ""
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[gallery]
name = "Gallery"
introduction = "An overview of all apps"
description = "The purpose of the Gallery is to enable you to get inspiration and locate the app you need"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "gallery"
servable = "src/apps/gallery/app.py"
thumbnail_url = "assets/images/thumbnails/gallery.png"
tags = []
category = "Main"
documentation_url = ""
code_url = ""
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[hello_panel_world_from_notebook_file]
name = "Hello Panel .ipynb World"
introduction = "A very simple Panel Hello World app developed in a .ipynb NOTEBOOK"
description = "A very simple Panel Hello World app developed in a .ipynb NOTEBOOK"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "hello-panel-world-from-notebook"
servable = "src/apps/hello_panel_world/app.ipynb"
thumbnail_url = "assets/images/thumbnails/hello-panel-world.png"
tags = []
category = "Panel Apps"
documentation_url = ""
code_url = ""
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[hello_panel_world_from_python_file]
name = "Hello Panel .py World"
introduction = "A very simple Panel Hello World app developed in a .py FILE"
description = "A very simple Panel Hello World app developed in a .py FILE"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "hello-panel-world-from-file"
servable = "src/apps/hello_panel_world/app.py"
thumbnail_url = "assets/images/thumbnails/hello-panel-world.png"
tags = []
category = "Panel Apps"
documentation_url = ""
code_url = ""
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[hello_ipywidgets_world_from_notebook_file]
name = "Hello Ipywidgets .ipynb World"
introduction = "A very simple Ipywidgets Hello World app developed in a .ipynb NOTEBOOK"
description = "A very simple Ipywidgets Hello World app developed in a .ipynb NOTEBOOK"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "hello-ipywidgets-world-from-notebook"
servable = "src/apps/hello_ipywidgets_world/app.ipynb"
thumbnail_url = "assets/images/thumbnails/hello-ipywidgets-world.png"
tags = []
category = "Ipywidgets Apps"
documentation_url = ""
code_url = ""
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[hello_ipywidgets_world_from_python_file]
name = "Hello Ipywidgets .py World"
introduction = "A very simple Ipywidgets Hello World app developed in a .py FILE"
description = "A very simple Ipywidgets Hello World app developed in a .py FILE"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "hello-ipywidgets-world-from-file"
servable = "src/apps/hello_ipywidgets_world/app.py"
thumbnail_url = "assets/images/thumbnails/hello-ipywidgets-world.png"
tags = []
category = "Ipywidgets Apps"
documentation_url = ""
code_url = ""
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[hello_bokeh_world_from_notebook_file]
name = "Hello Bokeh .ipynb World"
introduction = "A very simple Hello World app developed in a .ipynb NOTEBOOK"
description = "A very simple Hello World app developed in a .ipynb NOTEBOOK"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "hello-bokeh-world-from-notebook"
servable = "src/apps/hello_bokeh_world/app.ipynb"
thumbnail_url = "assets/images/thumbnails/hello-bokeh-world.png"
tags = []
category = "Bokeh Apps"
documentation_url = ""
code_url = ""
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[hello_bokeh_world_from_python_file]
name = "Hello Bokeh .py World"
introduction = "A very simple Bokeh Hello World app developed in a .py FILE"
description = "A very simple Bokeh Hello World app developed in a .py FILE"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "hello-bokeh-world-from-file"
servable = "src/apps/hello_bokeh_world/app.py"
thumbnail_url = "assets/images/thumbnails/hello-bokeh-world.png"
tags = []
category = "Bokeh Apps"
documentation_url = ""
code_url = ""
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[holoviews_linked_selections]
name = "HoloViews Linked Selections"
introduction = "A demonstration of HoloViews linked selections for Bokeh and Plotly backends"
description = "Returns an example app using the OrstedGalleryTemplate"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "holoviews-linked-selections"
servable = "src/apps/holoviews_linked_selections/app.py"
thumbnail_url = "assets/images/thumbnails/holoviews-linked-selections.png"
tags = []
category = "Panel Apps"
documentation_url = ""
code_url = "https://github.com/MarcSkovMadsen/awesome-analytics-apps-template/blob/main/src/apps/holoviews_linked_brushing.py"
mp4_url = "assets/videos/mp4s/holoviews-linked-selections.mp4"
youtube_url = ""
gif_url = ""
binder_url = ""

[streaming_dashboard]
name = "Streaming Dashboard"
introduction = "A demonstration of a Streaming Dashboard"
description = "A demonstration of a Streaming Dashboard"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "streaming-dashboard"
servable = "src/apps/streaming_dashboard/app.py"
thumbnail_url = "assets/images/thumbnails/streaming-dashboard.png"
tags=["Streaming", "Dashboard", "StatsCard"]
category = "Panel Apps"
documentation_url = ""
code_url = "https://github.com/MarcSkovMadsen/awesome-analytics-apps-template/blob/main/src/apps/streaming_dashboard/app.py"
mp4_url = "assets/videos/mp4s/streaming-dashboard.mp4.mp4"
youtube_url = ""
gif_url = ""
binder_url = ""

[streaming_plots]
name = "Streaming plots"
introduction = "A demonstration of a Streaming plots"
description = "A demonstration of a Streaming plots"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "streaming-plots"
servable = "src/apps/streaming_plots/app.py"
thumbnail_url = "assets/images/thumbnails/streaming-plots.png"
tags=["Streaming", "Streamz", "Plots"]
category = "Panel Apps"
documentation_url = ""
code_url = "https://github.com/MarcSkovMadsen/awesome-analytics-apps-template/blob/main/src/apps/streaming_plots/app.py"
mp4_url = "assets/videos/mp4s/streaming-plots.mp4.mp4"
youtube_url = ""
gif_url = ""
binder_url = ""

[ipyvolume_simple]
name = "IpyVolume"
introduction = "Simple IpyVolume example to show we can use it in the template"
description = "Simple IpyVolume example to show we can use it in the template"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "ipyvolume-simple"
servable = "src/apps/ipyvolume_simple/app.py"
thumbnail_url = "assets/images/thumbnails/ipyvolume-simple.png"
tags=["Ipywidgets", "IpyVolume"]
category = "Ipywidgets Apps"
documentation_url = ""
code_url = "https://github.com/MarcSkovMadsen/awesome-analytics-apps-template/blob/main/src/apps/ipyvolume_simple/app.py"
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""

[bokeh_movie_explorer]
name = "Bokeh Movie Explorer"
introduction = "The Bokeh Movie Explorer is a tool for exploring OMDB movie data"
description = "The Bokeh Movie Explorer is a tool for exploring OMDB movie data"
author = "marc_skov_madsen"
owner = "marc_skov_madsen"
url = "bokeh-movie-explorer"
servable = "src/apps/bokeh_movie_explorer/app.py"
thumbnail_url = "assets/images/thumbnails/bokeh-movie-explorer.png"
tags=["Bokeh"]
category = "Bokeh Apps"
documentation_url = ""
code_url = "https://github.com/MarcSkovMadsen/awesome-analytics-apps-template/blob/main/src/apps/bokeh_movie_explorer/app.py"
mp4_url = ""
youtube_url = ""
gif_url = ""
binder_url = ""