site_name = "Awesome Panel"
site_prefix = ""

gallery_description = "Search and find your app or other resource"

color_primary = "#A01346"
color_cycle = ["#A01346"]

[static_dirs]
assets = "src/assets"